services:
  seat_allocation:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    depends_on:
      - supabase
    networks:
      - ticketmaster_network

  supabase:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - ticketmaster_network

networks:
  ticketmaster_network:
    driver: bridge