services:
  ticket:
    build: .
    container_name: ticket_service
    ports:
      - "5000:5000"
    environment:
      - dbURL=${DATABASE_URL}
    env_file:
      - .env
    networks:
      - ticketmaster_network

networks:
  ticketmaster_network:
    driver: bridge
