services:
  ticket:
    build: ./atomic/ticket
    container_name: ticket_service
    ports:
      - "8501:5005"
    environment:
      - dbURL=${TICKET_DB_URL}
      - SEAT_ALLOC_SERVICE_URL=${SEAT_ALLOC_SERVICE_URL}
    env_file:
      - .env
    networks:
      - ticketmaster_network

  seat_allocation:
    build: ./atomic/seat_allocation
    container_name: seatalloc_service
    ports:
      - "8502:5000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    env_file:
      - .env
    networks:
      - ticketmaster_network

  payment:
    build: ./atomic/payment
    container_name: payment_service
    ports:
      - "8503:5001"
    environment:
      - dbURL=${PAYMENT_DB_URL}
    env_file:
      - .env
    networks:
      - ticketmaster_network

  buy_ticket:
    build: ./composite/buy_ticket
    container_name: buy_ticket_service
    ports:
      - "8504:8002"
    depends_on:
      - seat_allocation
      - payment
      - ticket
    networks:
      - ticketmaster_network

  trade_ticket:
    build: ./composite/trade_ticket
    container_name: trade_ticket_service
    ports:
      - "8505:8003"
    depends_on:
      - seat_allocation
      - payment
      - ticket
    networks:
      - ticketmaster_network

  cancel_ticket:
    build: ./composite/cancel_ticket
    container_name: cancel_ticket_service
    ports:
      - "8506:6001"
    depends_on:
      - seat_allocation
      - payment
      - ticket
    networks:
      - ticketmaster_network

  verify_ticket:
    build: ./composite/verify_ticket
    container_name: verify_ticket_service
    ports:
      - "8507:6002"
    depends_on:
      - ticket
      - seat_allocation
    networks:
      - ticketmaster_network

  kong:
    image: kong/kong-gateway:3.9
    container_name: kong
    restart: always
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yaml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_ADMIN_GUI_URL: http://localhost:8202
    volumes:
      - ./kong.yaml:/usr/local/kong/declarative/kong.yaml
    ports:
      - "8000:8000" # Public API gateway port
      - "8001:8001" # Admin API (CLI/config)
      - "8202:8002" # Kong Manager (GUI)
    networks:
      - ticketmaster_network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ticketmaster_network

networks:
  ticketmaster_network:
    driver: bridge

volumes:
  pgdata:
  rabbitmq_data:
